## Modified from https://github.com/vpetrigo/arm-cmake-toolchains/blob/master/.travis.yml
language: cpp
dist: xenial
sudo: required
branches:
  only:
    - master

matrix:
  fast_finish: true
  include:

    # ARM GCC (Linux)
    - os: linux
      name: "Linux ARM GCC"
      env:
        - "C_COMPILER=arm-none-eabi-gcc"
        - "CXX_COMPILER=arm-none-eabi-g++"
        - "SIZE=arm-none-eabi-size"
        - "OBJCOPY=arm-none-eabi-objcopy"
        - "LINKER=arm-none-eabi-ld"
        - "LLD=arm-none-eabi-ld.bfd"
        - "USE_NINJA=1"
      before_install:
        - sudo apt-get purge -y cmake
      addons:
        apt:
          sources:
            - sourceline: 'ppa:team-gcc-arm-embedded/ppa'
            - sourceline: 'deb https://apt.kitware.com/ubuntu/ xenial main'
              key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'
          packages:
            - ninja-build
            - cmake
            - gcc-arm-embedded
          update: true

    - os: linux
      name: "Linux ARM GCC Make"
      env:
        - "C_COMPILER=arm-none-eabi-gcc"
        - "CXX_COMPILER=arm-none-eabi-g++"
        - "SIZE=arm-none-eabi-size"
        - "OBJCOPY=arm-none-eabi-objcopy"
        - "LINKER=arm-none-eabi-ld"
        - "LLD=arm-none-eabi-ld.bfd"
        - "USE_NINJA=0"
      before_install:
        - sudo apt-get purge -y cmake
      addons:
        apt:
          sources:
            - sourceline: 'ppa:team-gcc-arm-embedded/ppa'
            - sourceline: 'deb https://apt.kitware.com/ubuntu/ xenial main'
              key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'
          packages:
            - cmake
            - gcc-arm-embedded
          update: true
    
    # ARM GCC (macOS)
    - os: osx
      osx_image: xcode10.1
      name: "Mac OSX ARM GCC"
      env:
        - "C_COMPILER=arm-none-eabi-gcc"
        - "CXX_COMPILER=arm-none-eabi-g++"
        - "SIZE=arm-none-eabi-size"
        - "OBJCOPY=arm-none-eabi-objcopy"
        - "LINKER=arm-none-eabi-ld"
        - "LLD=arm-none-eabi-ld.bfd"
        - "USE_NINJA=1"
      addons:
        homebrew:
          taps: ArmMbed/homebrew-formulae
          packages:
            - ninja
            - cmake
            - arm-none-eabi-gcc
          update: true

    - os: osx
      osx_image: xcode10.1
      name: "Mac OSX ARM GCC Make"
      env:
        - "C_COMPILER=arm-none-eabi-gcc"
        - "CXX_COMPILER=arm-none-eabi-g++"
        - "SIZE=arm-none-eabi-size"
        - "OBJCOPY=arm-none-eabi-objcopy"
        - "LINKER=arm-none-eabi-ld"
        - "LLD=arm-none-eabi-ld.bfd"
        - "USE_NINJA=0"
      addons:
        homebrew:
          taps: ArmMbed/homebrew-formulae
          packages:
            - cmake
            - arm-none-eabi-gcc
          update: true

script:
  - sh ci/exec.sh

notifications:
  email: false