## Modified from https://github.com/vpetrigo/arm-cmake-toolchains/blob/master/.travis.yml
language: cpp
dist: xenial
branches:
  only:
    - master

matrix:
  fast_finish: true
  include:

    # ARM GCC (Linux)
    - os: linux
      name: "ARM GCC"
      env:
        - "C_COMPILER=arm-none-eabi-gcc"
        - "CXX_COMPILER=arm-none-eabi-g++"
        - "SIZE=arm-none-eabi-size"
        - "OBJCOPY=arm-none-eabi-objcopy"
        - "LINKER=arm-none-eabi-ld"
        - "LLD=arm-none-eabi-ld.bfd"
        - "USE_NINJA=1"
      addons:
        apt:
          packages:
            - ninja-build

    - os: linux
      name: "ARM GCC Make"
      env:
        - "C_COMPILER=arm-none-eabi-gcc"
        - "CXX_COMPILER=arm-none-eabi-g++"
        - "SIZE=arm-none-eabi-size"
        - "OBJCOPY=arm-none-eabi-objcopy"
        - "LINKER=arm-none-eabi-ld"
        - "LLD=arm-none-eabi-ld.bfd"
        - "USE_NINJA=0"

script:
  - sh ci/exec.sh

notifications:
  email: false