## Modified from https://github.com/vpetrigo/arm-cmake-toolchains/blob/master/.travis.yml
language: cpp
dist: xenial
branches:
  only:
    - master

matrix:
  fast_finish: true
  include:

    # ARM GCC (Linux)
    - os: linux
      name: "ARM GCC"
      env:
        - "C_COMPILER=arm-none-eabi-gcc"
        - "CXX_COMPILER=arm-none-eabi-g++"
        - "SIZE=arm-none-eabi-size"
        - "OBJCOPY=arm-none-eabi-objcopy"
        - "LINKER=arm-none-eabi-ld"
        - "LLD=arm-none-eabi-ld.bfd"
        - "USE_NINJA=1"
      addons:
        apt:
          packages:
            - ninja-build

    - os: linux
      name: "ARM GCC Make"
      env:
        - "C_COMPILER=arm-none-eabi-gcc"
        - "CXX_COMPILER=arm-none-eabi-g++"
        - "SIZE=arm-none-eabi-size"
        - "OBJCOPY=arm-none-eabi-objcopy"
        - "LINKER=arm-none-eabi-ld"
        - "LLD=arm-none-eabi-ld.bfd"
        - "USE_NINJA=0"

    # Clang/LLVM + ARM GCC (Linux)
    - os: linux
      name: "Clang 6.0"
      env:
        - "C_COMPILER=clang-6.0"
        - "CXX_COMPILER=clang++-6.0"
        - "SIZE=llvm-size-6.0"
        - "OBJCOPY=llvm-objcopy-6.0"
        - "LINKER=lld-6.0"
        - "LLD=ld.lld-6.0"
        - "USE_NINJA=1"
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-6.0
          packages:
            - clang-6.0
            - llvm-6.0
            - lld-6.0
            - ninja-build

    - os: linux
      name: "Clang 7.0"
      env:
        - "C_COMPILER=clang-7"
        - "CXX_COMPILER=clang++-7"
        - "SIZE=llvm-size-7"
        - "OBJCOPY=llvm-objcopy-7"
        - "LINKER=lld-7"
        - "LLD=ld.lld-7"
        - "USE_NINJA=1"
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-7
          packages:
            - clang-7
            - llvm-7
            - lld-7
            - ninja-build

    - os: linux
      name: "Clang 8.0"
      env:
        - "C_COMPILER=clang-8"
        - "CXX_COMPILER=clang++-8"
        - "SIZE=llvm-size-8"
        - "OBJCOPY=llvm-objcopy-8"
        - "LINKER=lld-8"
        - "LLD=ld.lld-8"
        - "USE_NINJA=1"
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-8
          packages:
            - clang-8
            - llvm-8
            - lld-8
            - ninja-build

script:
  - sh ci/exec.sh